apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: %name% 
  labels:
    app: %name%
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: %name%
    spec:
      containers:
      - name: default-container
        image: busybox:latest
        env:
        - name: APPLICATION_NAME
          value: %name%
        ports:
        - containerPort: 8080 
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
        - default-container
      from:
        kind: ImageStreamTag
        name: %name%:latest 
    type: ImageChange
  - type: ConfigChange
